spring.application.name=API-Gateway
spring.config.import=classpath:routes.yml
rlaas.apikey=TD34k-AhiFhEO-Oy_z1dZeDJJA4HOTCo-t-mHarebYM
eureka.client.service-url.defaultZone=http://service-discovery:8081/eureka/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=true
