spring.application.name=API-Gateway
spring.config.import=classpath:routes.yml
rlaas.apikey=eHqTdrrIgdVjPf0hF1xdTR9lyKcxKpWtArWZznefnbg
eureka.client.service-url.defaultZone=http://localhost:8081/eureka/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=true
