routes:
  /profile:
    serviceName: SAMPLE-MICROSERVICE-1
    allowedMethods: 
    - GET
    - POST
    - DELETE
    requiredHeaders: 
    - X-API-KEY
    authRequired: true
  /product:
    serviceName: SAMPLE-MICROSERVICE-2
    allowedMethods: 
    - GET
    authRequired: false
  /order:
    serviceName: SAMPLE-MICROSERVICE-2
    allowedMethods: 
    - GET
    authRequired: false
